{
  "formatVersion": "1.1",
  "component": {
    "group": "net.fabricmc",
    "module": "fabric-loom",
    "version": "1.11-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.14",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fabric-loom-1.11-SNAPSHOT.jar",
          "url": "fabric-loom-1.11-SNAPSHOT.jar",
          "size": 1157927,
          "sha512": "67c2eac13d62285bdf5b96aee68c4a3b2c861d6f837c1311afefcbb165087655e0c536723a48397ecdd0b9344a616100de7ba06a0f9d6d1f50812b9d467c1844",
          "sha256": "ddfccbfea630c13d720fe8b899087a09c46b16832f9823541dcfaf4fbbf15ae6",
          "sha1": "f77e5cafb060310b4800b959d6c1594bbc5a9641",
          "md5": "48dd53549894edbc81b005ea8924f1d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.14",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-jre"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.11.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "access-widener",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mapping-io",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "lorenz-tiny",
          "version": {
            "requires": "4.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loom-native",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mercury",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "net.fabricmc.unpick",
          "module": "unpick",
          "version": {
            "requires": "3.0.0-beta.5"
          }
        },
        {
          "group": "net.fabricmc.unpick",
          "module": "unpick-format-utils",
          "version": {
            "requires": "3.0.0-beta.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-metadata-jvm",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fabric-loom-1.11-SNAPSHOT.jar",
          "url": "fabric-loom-1.11-SNAPSHOT.jar",
          "size": 1157927,
          "sha512": "67c2eac13d62285bdf5b96aee68c4a3b2c861d6f837c1311afefcbb165087655e0c536723a48397ecdd0b9344a616100de7ba06a0f9d6d1f50812b9d467c1844",
          "sha256": "ddfccbfea630c13d720fe8b899087a09c46b16832f9823541dcfaf4fbbf15ae6",
          "sha1": "f77e5cafb060310b4800b959d6c1594bbc5a9641",
          "md5": "48dd53549894edbc81b005ea8924f1d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.14",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fabric-loom-1.11-SNAPSHOT-sources.jar",
          "url": "fabric-loom-1.11-SNAPSHOT-sources.jar",
          "size": 659800,
          "sha512": "c3f041146142bca8ccf4e130ee3121023a4f46d83685f73a5aa62738e256e428a098b491bd8f1004c42b8bd500ae8ebc56ca9766a5e9d517c3846f7dc2225217",
          "sha256": "ff336efd0fa04fda1591cee12e0e35f53a3b790b2a25430493ea7baf35e4aab4",
          "sha1": "6d8aec8ba95846e2b7e3e15504174565ad125c91",
          "md5": "06b09c18007649c45c58bc7023e0dffb"
        }
      ]
    }
  ]
}
